name: Build CLI
on:
  push:
  pull_request:
  release:
    types: [published]
 
env:
  TAG: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       # Boost and GCC PI
      - name: Configurar herramientas
        run: |
          sudo apt update
          sudo apt install -y g++-arm-linux-gnueabihf build-essential python3-dev
      - name: Descargar Boost
        run: |
          wget https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.gz
          tar -xzf boost_1_80_0.tar.gz
          cd boost_1_80_0
          ./bootstrap.sh --with-libraries=system,filesystem,thread,date_time,chrono,regex,serialization,atomic,program_options,locale,timer,log
          ./b2 toolset=gcc cxxflags="-march=armv7-a -mfpu=neon -mfloat-abi=hard"
