name: Build CLI
on:
  push:
  pull_request:
  release:
    types: [published]
 
env:
  TAG: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       # Boost and GCC PI
      - name: Configurar herramientas
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf build-essential python3-dev
      - name: Descargar Boost
        run: |
          wget https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.gz
          tar -xzf boost_1_81_0.tar.gz
          cd boost_1_81_0
          gcc-arm-linux-gnueabihf --version
          export CC=gcc-arm-linux-gnueabihf
          export CXX=g++-arm-linux-gnueabihf
          ./bootstrap.sh
          ./b2 toolset=gcc-arm target-os=linux address-model=32 architecture=arm abi=aapcs binary-format=elf \
          cxxflags="-march=armv7-a -mfpu=neon -mfloat-abi=hard" \
          linkflags="-march=armv7-a -mfpu=neon -mfloat-abi=hard" \
          threading=multi -j$(nproc)

          
            
