name: Build Boost for ARM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # Usamos Ubuntu como base para el trabajo

    steps:
      - name: Check out repository
        uses: actions/checkout@v3  # Para obtener el código fuente del repositorio

      - name: Set up cross-compilation toolchain
        run: |
          sudo apt update
          sudo apt install -y build-essential g++-arm-linux-gnueabihf gcc-arm-linux-gnueabihf wget tar

      - name: Download and extract Boost
        run: |
          wget https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.gz
          tar -xzf boost_1_81_0.tar.gz

      - name: Create user-config.jam for cross-compilation
        run: |
          echo "using gcc : arm : /usr/bin/arm-linux-gnueabihf-gcc : /usr/bin/arm-linux-gnueabihf-g++ ;" > boost_1_81_0/user-config.jam
          cat boost_1_81_0/user-config.jam  

      - name: Set environment variables for cross-compilation
        run: |
          export CC=/usr/bin/arm-linux-gnueabihf-gcc
          export CXX=/usr/bin/arm-linux-gnueabihf-g++

      - name: Build Boost
        run: |
          cd boost_1_81_0
          rm -rf boost_1_81_0/tools/build/*
          ./bootstrap.sh
          ./b2 toolset=gcc-arm stage
          ./b2 toolset=gcc-arm install --prefix=/home/runner/work/Infinium/Infinium/boost

      - name: Verify Boost installation
        run: |
          ls /usr/local/boost
