name: Build CLI
on:
  push:
  pull_request:
  release:
    types: [published]
 
env:
  TAG: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       # Boost and GCC PI
      - name: Configurar herramientas
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf build-essential python3-dev
      - name: Descargar Boost
        run: |
          wget https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.gz
          tar -xzf boost_1_81_0.tar.gz
          cd boost_1_81_0
          /usr/bin/arm-linux-gnueabihf-gcc --version
          /usr/bin/arm-linux-gnueabihf-g++ --version
          export CC=/usr/bin/arm-linux-gnueabihf-gcc
          export CXX=/usr/bin/arm-linux-gnueabihf-g++
          ./bootstrap.sh
          ./b2 toolset=gcc-arm target-os=linux address-model=32 architecture=arm abi=aapcs
