name: Build CLI
on:
  push:
  pull_request:
  release:
    types: [published]
 
env:
  TAG: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar dependencias
        run: |
          sudo apt update
          sudo apt install -y g++-arm-linux-gnueabihf make wget build-essential zlib1g-dev
          wget https://www.python.org/ftp/python/3.10.12/Python-3.10.12.tgz
          tar -xzf Python-3.10.12.tgz
          cd Python-3.10.12
          ./configure --host=arm-linux-gnueabihf --build=x86_64-linux-gnu --prefix=/opt/python-arm --enable-shared LDFLAGS="-L/usr/arm-linux-gnueabihf/lib" CPPFLAGS="-I/usr/arm-linux-gnueabihf/include" --disable-ipv6
          make
          make install
       # Boost and GCC PI
      - name: Configurar herramientas
        run: |
          sudo apt update
          sudo apt install -y g++-arm-linux-gnueabihf build-essential
      - name: Descargar Boost
        run: |
          wget https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.gz
          tar -xzf boost_1_80_0.tar.gz
          cd boost_1_80_0
      - name: Configurar Boost Build
        run: |
          cd boost_1_80_0
          pwd
          ./bootstrap.sh --prefix=${pwd}/boost
          echo "using gcc : arm : arm-linux-gnueabihf-g++ ;" > project-config.jam
      - name: Compilar Boost
        run: |
          cd boost_1_80_0
          ./b2 toolset=gcc-arm target-os=linux architecture=arm address-model=32 --with=all install
