name: Build Boost for ARM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # Usamos Ubuntu como base para el trabajo

    steps:
      - name: Check out repository
        uses: actions/checkout@v3  # Para obtener el código fuente del repositorio

      - name: Set up cross-compilation toolchain
        run: |
          sudo apt update
          sudo apt install -y build-essential g++-arm-linux-gnueabihf gcc-arm-linux-gnueabihf wget tar curl build-essential python3-dev autotools-dev libicu-dev libbz2-dev cmake git screen checkinstall zlib1g-dev

      - name: Download and extract Boost
        run: |
          wget https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.gz
          tar -xzf boost_1_81_0.tar.gz

      - name: Create user-config.jam for cross-compilation
        run: |
          echo "using gcc : arm : /usr/bin/arm-linux-gnueabihf-gcc : /usr/bin/arm-linux-gnueabihf-g++ ;" > boost_1_81_0/user-config.jam
          cat boost_1_81_0/user-config.jam  

      - name: Set environment variables for cross-compilation
        run: |
          export CC=/usr/bin/arm-linux-gnueabihf-gcc
          export CXX=/usr/bin/arm-linux-gnueabihf-g++

      - name: Build Boost
        run: |
          cd boost_1_81_0
          rm -rf boost_1_81_0/tools/build/*
          ./bootstrap.sh --with-libraries=system,filesystem,thread,date_time,chrono,regex,serialization,atomic,program_options,locale,timer,log
          ./b2 toolset=gcc-arm --user-config=user-config.jam --prefix=/home/runner/work/Infinium/Infinium/boost

      # Install OpenSSL
      - name: Install OpenSSL
        run: |
          curl -OL https://www.openssl.org/source/openssl-1.1.1n.tar.gz
          tar xaf openssl-1.1.1n.tar.gz 
          cd openssl-1.1.1n/
          ./config no-asm linux-armv4 --cross-compile-prefix=arm-linux-gnueabihf- --prefix=/home/runner/work/Infinium/Infinium/openssl --openssldir=/home/runner/work/Infinium/Infinium/openssl shared zlib
          make
          make install
